Repository Azure/sonic-build-tools, pull requests merged in 2020-08, with the labels that each got.

#133 [sairedis] Add VS tests to sairedis repo
  jenkins/vs/sonic-sairedis-build-pr/Jenkinsfile
  jenkins/vs/sonic-sairedis-build/Jenkinsfile
  scripts/vs/sonic-sairedis-build/build.sh
  scripts/vs/sonic-sairedis-build/docker-sonic-vs/Dockerfile
  scripts/vs/sonic-sairedis-build/docker_build_script.sh
Labels: enhancement

#141 [sonic-utilitites-build] Install sonic-py-common and archive artifacts
  jenkins/common/sonic-utilities-build-pr/Jenkinsfile
  jenkins/common/sonic-utilities-build/Jenkinsfile
  scripts/common/sonic-utilities-build/build.sh
Labels: enhancement

#143 [sonic-utilitites-build] Install sonic_config_engine after sonic_py_common
  scripts/common/sonic-utilities-build/build.sh
Labels: bug

#144 [sonic-utilities-build] Do not install Python 3 version of sonic-py-common for now
  scripts/common/sonic-utilities-build/build.sh
Labels: bug

#146 [utilities] Remove dependencies on latest swss and sairedis updates from utilities builds
  jenkins/common/sonic-utilities-build-pr/Jenkinsfile
  jenkins/common/sonic-utilities-build/Jenkinsfile
  scripts/common/sonic-utilities-build/build.sh
Labels: bug

#145 [vs] Rename 'veos.vtb' to 'veos_vtb'
  scripts/vs/buildimage-vs-image/runtest.sh
  scripts/vs/buildimage-vs-image/test.sh
Labels: Cleanup :droplet:

#147 [sairedis] Fix sairedis test setup
  scripts/vs/sonic-sairedis-build/build.sh
  scripts/vs/sonic-sairedis-build/docker-sonic-vs/Dockerfile
Labels: bug

#150 [kvm] Fix KVM results archival
  jenkins/mgmt/sonic-mgmt-canary/Jenkinsfile
  jenkins/mgmt/sonic-mgmt-pr/Jenkinsfile
  jenkins/vs/buildimage-vs-image-201911-test/Jenkinsfile
  jenkins/vs/buildimage-vs-image-pr/Jenkinsfile
  jenkins/vs/buildimage-vs-image/Jenkinsfile
  scripts/vs/buildimage-vs-image/runtest.sh
Labels: bug

#153 [vs] Fix issue of swss debian being overwritten by sairedis
  jenkins/vs/sonic-swss-build-pr/Jenkinsfile
  jenkins/vs/sonic-swss-build/Jenkinsfile
  scripts/vs/sonic-swss-build/build.sh
Labels: bug

#152 [vs] Install python-swsscommon inside the DVS image
  scripts/vs/sonic-sairedis-build/build.sh
  scripts/vs/sonic-sairedis-build/docker-sonic-vs/Dockerfile
  scripts/vs/sonic-swss-build/docker-sonic-vs/Dockerfile
Labels: bug
